name: multi project wxpython app built on mac
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: macos-latest
    steps:

    # - uses: actions/checkout@v2

    - name: Check out current repo into a subdir
      uses: actions/checkout@v2
      with:
        path: subdir/mainproj/

    - name: Check out my other private repo
      uses: actions/checkout@v2
      with:
        repository: abulka/relationship-manager
        # token: ${{ secrets.my_pat }}
        path: relationship-manager/

    - name: View resulting directory structure
      run: ls -lR

    - name: Setup Python please
      uses: actions/setup-python@v2
      with:
        python-version: 3.8    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wxpython
        pip install -r requirements.txt
        pip install pyinstaller
    - name: Run Python and print version_info
      run: |
        python -c "import sys; print(sys.version_info)"
        uname -a

    - name: runsimple
      run: |
        ./bin/runsimple

    # - name: Build executable using Pyinstaller
    #   run: |
    #     pyinstaller rubber_band_async_custom.spec
    #     ls -l dist/
    # - name: Save generated executable file as an artifact
    #   uses: actions/upload-artifact@v2
    #   with:
    #     # The act of downloading zips up the artifact and adds the .zip to the downloaded file
    #     name: rubber-band-${{ matrix.os }}
    #     path: dist/